import type { NextPage } from "next";
import Head from "next/head";
import Home from "../components/Home";
import { Fragment } from "react";

const App: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Wuzzles</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Home />
    </Fragment>
  );
};

export default App;
